### ISSUE TITLE
Commands are run via bash -c

### ISSUE THREAD

**Issue by mathstuf** [jD91mZM2/xidlehook#1]
I see from the source code that commands are run via `bash -c`. I think it'd be nicer to just have a simple command (maybe split on whitespace for arguments) and that can be a bash script rather than assuming `bash`. However, if `bash` is going to continue to be used, documenting it as such would be nice.

**Comment by jD91mZM2** [comment]
I like to use bash/sh because it works just like the user would expect. Stuff like `test; hello` works out of the box. I changed it to `sh` for now, since that's more known.

**Comment by mathstuf** [comment]
*shrug* IMO, it makes more sense to put those things into scripts that can be called from anywhere rather than just existing in a command line, but OK, the current solution still works for me.
