### ISSUE TITLE
Locking the screen on laptop close

### ISSUE THREAD

**Issue by CrashyBang** [jD91mZM2/xidlehook#10]
Currently I use `xss-lock` to lock my screen if I close my laptop like so:
```
xss-lock -- "$HOME/.utility/lock" &
```
Based on the description I would think that this sort of functionality should be left with `xss-lock` but I just wanted to double check, obviously if I could do both with `xidkehook` I would.

**Comment by jD91mZM2** [comment]
Not supported at the moment, though you could use xss-lock to trigger the timer using xidlehook sockets to better integrate it :)

**Comment by CrashyBang** [comment]
Hahaha I will have to do some googling to figure that one out, but I appreciate it :)

**Comment by overclockedllama** [comment]
Is there any plans to implement this any time soon?

**Comment by jD91mZM2** [comment]
There are not. I can reopen this issue if you feel like this is worth having built-in

**Comment by overclockedllama** [comment]
Nah don't worry about it. I added it using a systemd service run on suspend

On Mon, May 20, 2019, 8:16 AM jD91mZM2 <notifications@github.com<mailto:notifications@github.com>> wrote:

There are not. I can reopen this issue if you feel like this is worth having built-in
