### ISSUE TITLE
Failed to query x for input focus

### ISSUE THREAD

**Issue by CrashyBang** [jD91mZM2/xidlehook#13]
Sorry to open so many issues, this should be my last one.

When the timer executes I get the following error before my lock script runs:
```
warning: failed to query x for input focus
```

I think this is preventing the fullscreen flag from working.

**Comment by jD91mZM2** [comment]
Fixed in cbc3302e3485a8308d6ba5dd6b4d069d322908dd! Can you confirm?

**Comment by CrashyBang** [comment]
Can confirm this is working :)

**Comment by jD91mZM2** [comment]
Awesome, thanks!
