### ISSUE TITLE
howto: detect ac power to disable

### ISSUE THREAD

**Issue by senorsmile** [jD91mZM2/xidlehook#15]
Would it be possible using the existing version of xidlehook to detect when on AC power to disable 
 one of the "stages" (i.e. still start screensaver but do not suspend)?

**Comment by jD91mZM2** [comment]
Why not just check it with dash as one of the timers?
Such as:
```
--timer normal "on_ac_power && systemctl suspend" ""
``

**Comment by senorsmile** [comment]
Perfect!  Didn't know `on_ac_power` was even a thing.

**Comment by jpmorris** [comment]
For those on arch:
`grep 0 /sys/class/power_supply/AC/online > /dev/null && systemctl suspend`
