### ISSUE TITLE
--not-when-fullscreen for all windows, not just active one

### ISSUE THREAD

**Issue by jD91mZM2** [jD91mZM2/xidlehook#19]
Would it be possible to make this disable timers when *any* fullscreen application is running? Sometimes I have a video on one monitor while I work on another, and it would be nice to not have to remember to keep giving the video focus every time I leave my keyboard even though me (or my toddler) is still watching.

_Originally posted by @jpmorris in https://github.com/jD91mZM2/xidlehook/issues/5#issuecomment-475853721_

**Comment by jpmorris** [comment]
thanks so much for the hard work! I'll try --not-when-audio and see if that works for me

**Comment by jD91mZM2** [comment]
Alright, does the latest master work as you'd expect? I made it check all windows instead
