### ISSUE TITLE
less flick when dim and lock

### ISSUE THREAD

**Issue by tmpm697** [jD91mZM2/xidlehook#21]
I have screen at 80% to test this software feature. From 80% dims to `.1`causes screen go directly from 80% to `.1` and it looks like a `flick`, sudden change doesn't look well on user experience.

I'm suggesting that instead go directly from X to `.1`, do a loop that change brightness from `X->X-1->X-2->...->.1`

and when user active, go from `.1->2->..->X`

Another issue: I use `slock` to lock after 10 seconds, each time `xidlehook` calls `slock` screen do a `flash`. I guess this dues to when calling `slock`, `xidlehook` brings back brightness at 80% then do `lock` screen. If we can turn off screen `xset dpms force off` then do `lock` screen, and then set brightness to 80% (in background), this would might avoid flick/flash for this issue.

Thanks.

**Comment by jD91mZM2** [comment]
Xidlehook does not have anything with rendering the screen to do, that is up to you and your timers. If you want to write a bash script to fade the screen differently than the one in the README, feel free, nothing is stopping you!
