### ISSUE TITLE
Query xidlelock disabled/enabled

### ISSUE THREAD

**Issue by mindrunner** [jD91mZM2/xidlehook#29]
I would like to query if I am in disabled or enabled state and maybe even if there is something (e.g. a full screen video) inhibiting the screensaver. 

Use case:
i3bar displaying whether screensaver is on or off as well as toggling the functionality from there.

Is there any option to get this information or do we need to extend `xidlehook-client` with the parameters `--toggle` and `--query`?

**Comment by jD91mZM2** [comment]
Would probably be implemented together with #27

**Comment by jD91mZM2** [comment]
Yeah this is fixed now, I forgot to clean up the issue list after [!6](https://gitlab.com/jD91mZM2/xidlehook/merge_requests/6)
