### ISSUE TITLE
Compiling with --no-default-features still requries libpulse

### ISSUE THREAD

**Issue by twooster** [jD91mZM2/xidlehook#32]
## Expected Behavior:
Installing with the `--no-default-features` flag should not depend upon libpulse.

## Observed Behavior:
Installing with the `--no-default-features` flag still requires libpulse.

## Discussion
This bug prevents me from installing `xidlehook` on Ubuntu 18.04 LTS, because the latest supported version of libpulse is 11, but xidlehook requires libpulse 12. This was fine with
0.7.1, because I could easily run:

```
cargo install --no-default-features xidlehook --version 0.7.1
```

And the install would successfully build without requiring/using libpulse at all. The latest version, 0.8, however, does not support this.

**Comment by jD91mZM2** [comment]
Turns out I fixed this and didn't release a new patch version. Sorry about that, I'm not used to people using my stuff and didn't wanna spam crates.io I assume. Fixed now, as 0.8.1 :)
