### ISSUE TITLE
--not-when-fullscreen not detecting wine games

### ISSUE THREAD

**Issue by fuzunspm** [jD91mZM2/xidlehook#47]
Hi,

I'm using i3gaps, xidlehook and i3lock together. It normally works but recently i discovered when i was away from keyboard that xidlehook won't detect wine games even they are fullscreen.

```
exec --no-startup-id xidlehook --not-when-fullscreen --timer 300 "i3lock -f -B=sigma -k --pass-media-keys --timecolor=ffffffff --datecolor=ffffffff" ""
```

xidlehook 0.8.2
i3 version 4.18.1
5.6.15-arch1-1

**Comment by jD91mZM2** [comment]
How does the latest master, 31a658b3aeda9a389864157f6b0a91bf8ea1b281, work for you? Most people having trouble with `--not-when-fullscreen` has been because it didn't check all windows. I recently needed this myself, so I fixed it.

**Comment by fuzunspm** [comment]
we may close this issue since it was caused by X monitor power off setting
