### ISSUE TITLE
The xidlehook-client add command doesn't properly take all options into account

### ISSUE THREAD

**Issue by blubber** [jD91mZM2/xidlehook#59]
As far as I can tell from the documentation the following command should result in a new timer, with a activation **and** a cancelation command:

`$ xidlehook-client add --time 300 --activation activate --abortion abort`

Instead, the resulting timer looks like this:
```
$ xidlehook-client query --timer 3
QueryResult(
    [
        QueryResult {
            timer: 3,
            time: 300s,
            activation: [
                "activate",
                "--abortion",
                "abort",
            ],
            abortion: [],
            deactivation: [],
            disabled: false,
        },
    ],
)
```

**Comment by jD91mZM2** [comment]
`xidlehook-client add --time 300 --activation activate \; --abortion abort` should do the trick :)

**Comment by blubber** [comment]
Cool, thanks for the quick reply!
